<a href="https://colab.research.google.com/github/r-kubo/Studies/blob/master/%E3%83%93%E3%82%B8%E3%83%8D%E3%82%B9AI%E6%B4%BB%E7%94%A8%E5%8B%89%E5%BC%B7%E4%BC%9A/%E7%AC%AC1%E5%9B%9E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
data = pd. read_csv("iris.csv" , engine="python" , encoding="s-jis")

In [5]:
data

がく片  がく片幅  花びら  花びら幅      あやめ
0    5.0   3.3  1.4   0.2      ｾﾄﾅ
1    6.4   2.8  5.6   2.2  ﾊﾞｰｼﾞﾆｶ
2    6.5   2.8  4.6   1.5   ﾊﾞｰｼｸﾙ
3    6.7   3.1  5.6   2.4  ﾊﾞｰｼﾞﾆｶ
4    6.3   2.8  5.1   1.5  ﾊﾞｰｼﾞﾆｶ
5    4.6   3.4  1.4   0.3      ｾﾄﾅ
6    6.9   3.1  5.1   2.3  ﾊﾞｰｼﾞﾆｶ
7    6.2   2.2  4.5   1.5   ﾊﾞｰｼｸﾙ
8    5.9   3.2  4.8   1.8   ﾊﾞｰｼｸﾙ
9    4.6   3.6  1.0   0.2      ｾﾄﾅ
10   6.1   3.0  4.6   1.4   ﾊﾞｰｼｸﾙ
11   6.0   2.7  5.1   1.6   ﾊﾞｰｼｸﾙ
12   6.5   3.0  5.2   2.0  ﾊﾞｰｼﾞﾆｶ
13   5.6   2.5  3.9   1.1   ﾊﾞｰｼｸﾙ
14   6.5   3.0  5.5   1.8  ﾊﾞｰｼﾞﾆｶ
15   5.8   2.7  5.1   1.9  ﾊﾞｰｼﾞﾆｶ
16   6.8   3.2  5.9   2.3  ﾊﾞｰｼﾞﾆｶ
17   5.1   3.3  1.7   0.5      ｾﾄﾅ
18   5.7   2.8  4.5   1.3   ﾊﾞｰｼｸﾙ
19   6.2   3.4  5.4   2.3  ﾊﾞｰｼﾞﾆｶ
20   7.7   3.8  6.7   2.2  ﾊﾞｰｼﾞﾆｶ
21   6.3   3.3  4.7   1.6   ﾊﾞｰｼｸﾙ
22   6.7   3.3  5.7   2.5  ﾊﾞｰｼﾞﾆｶ
23   7.6   3.0  6.6   2.1  ﾊﾞｰｼﾞﾆｶ
24   4.9   2.5  4.5   1.7  ﾊﾞｰｼﾞﾆｶ
25   5.5   3.5  1.3   0.2      ｾﾄﾅ
26   6.7   3.0  5.2   2.3  ﾊﾞｰｼﾞﾆｶ
27   7.0   3.2  4.7   1.4   ﾊﾞｰｼｸﾙ
28   6.4   3.2  4.5   1.5   ﾊﾞｰｼｸﾙ
29   6.1   2.8  4.0   1.3   ﾊﾞｰｼｸﾙ
..   ...   ...  ...   ...      ...
120  5.7   2.8  4.1   1.3   ﾊﾞｰｼｸﾙ
121  6.5   3.0  5.8   2.2  ﾊﾞｰｼﾞﾆｶ
122  6.9   3.1  5.4   2.1  ﾊﾞｰｼﾞﾆｶ
123  5.4   3.9  1.3   0.4      ｾﾄﾅ
124  5.1   3.5  1.4   0.3      ｾﾄﾅ
125  7.2   3.6  6.1   2.5  ﾊﾞｰｼﾞﾆｶ
126  6.5   3.2  5.1   2.0  ﾊﾞｰｼﾞﾆｶ
127  6.1   2.9  4.7   1.4   ﾊﾞｰｼｸﾙ
128  5.6   2.9  3.6   1.3   ﾊﾞｰｼｸﾙ
129  6.9   3.1  4.9   1.5   ﾊﾞｰｼｸﾙ
130  6.4   2.7  5.3   1.9  ﾊﾞｰｼﾞﾆｶ
131  6.8   3.0  5.5   2.1  ﾊﾞｰｼﾞﾆｶ
132  5.5   2.5  4.0   1.3   ﾊﾞｰｼｸﾙ
133  4.8   3.4  1.6   0.2      ｾﾄﾅ
134  4.8   3.0  1.4   0.1      ｾﾄﾅ
135  4.5   2.3  1.3   0.3      ｾﾄﾅ
136  5.7   2.5  5.0   2.0  ﾊﾞｰｼﾞﾆｶ
137  5.7   3.8  1.7   0.3      ｾﾄﾅ
138  5.1   3.8  1.5   0.3      ｾﾄﾅ
139  5.5   2.3  4.0   1.3   ﾊﾞｰｼｸﾙ
140  6.6   3.0  4.4   1.4   ﾊﾞｰｼｸﾙ
141  6.8   2.8  4.8   1.4   ﾊﾞｰｼｸﾙ
142  5.4   3.4  1.7   0.2      ｾﾄﾅ
143  5.1   3.7  1.5   0.4      ｾﾄﾅ
144  5.2   3.5  1.5   0.2      ｾﾄﾅ
145  5.8   2.8  5.1   2.4  ﾊﾞｰｼﾞﾆｶ
146  6.7   3.0  5.0   1.7   ﾊﾞｰｼｸﾙ
147  6.3   3.3  6.0   2.5  ﾊﾞｰｼﾞﾆｶ
148  5.3   3.7  1.5   0.2      ｾﾄﾅ
149  5.0   2.3  3.3   1.0   ﾊﾞｰｼｸﾙ

[150 rows x 5 columns]

In [10]:
data_setosa = data[data["あやめ"] == "ｾﾄﾅ"]
data_setosa. mean ()

がく片     5.006
がく片幅    3.428
花びら     1.462
花びら幅    0.246
dtype: float64

In [13]:
data_even = data[(data .index % 2) == 0]
data_even

がく片  がく片幅  花びら  花びら幅      あやめ
0    5.0   3.3  1.4   0.2      ｾﾄﾅ
2    6.5   2.8  4.6   1.5   ﾊﾞｰｼｸﾙ
4    6.3   2.8  5.1   1.5  ﾊﾞｰｼﾞﾆｶ
6    6.9   3.1  5.1   2.3  ﾊﾞｰｼﾞﾆｶ
8    5.9   3.2  4.8   1.8   ﾊﾞｰｼｸﾙ
10   6.1   3.0  4.6   1.4   ﾊﾞｰｼｸﾙ
12   6.5   3.0  5.2   2.0  ﾊﾞｰｼﾞﾆｶ
14   6.5   3.0  5.5   1.8  ﾊﾞｰｼﾞﾆｶ
16   6.8   3.2  5.9   2.3  ﾊﾞｰｼﾞﾆｶ
18   5.7   2.8  4.5   1.3   ﾊﾞｰｼｸﾙ
20   7.7   3.8  6.7   2.2  ﾊﾞｰｼﾞﾆｶ
22   6.7   3.3  5.7   2.5  ﾊﾞｰｼﾞﾆｶ
24   4.9   2.5  4.5   1.7  ﾊﾞｰｼﾞﾆｶ
26   6.7   3.0  5.2   2.3  ﾊﾞｰｼﾞﾆｶ
28   6.4   3.2  4.5   1.5   ﾊﾞｰｼｸﾙ
30   4.8   3.1  1.6   0.2      ｾﾄﾅ
32   5.5   2.4  3.8   1.1   ﾊﾞｰｼｸﾙ
34   6.4   3.2  5.3   2.3  ﾊﾞｰｼﾞﾆｶ
36   4.9   3.6  1.4   0.1      ｾﾄﾅ
38   7.9   3.8  6.4   2.0  ﾊﾞｰｼﾞﾆｶ
40   6.7   3.3  5.7   2.1  ﾊﾞｰｼﾞﾆｶ
42   5.8   2.6  4.0   1.2   ﾊﾞｰｼｸﾙ
44   7.7   2.8  6.7   2.0  ﾊﾞｰｼﾞﾆｶ
46   4.7   3.2  1.6   0.2      ｾﾄﾅ
48   7.2   3.2  6.0   1.8  ﾊﾞｰｼﾞﾆｶ
50   5.1   3.8  1.6   0.2      ｾﾄﾅ
52   4.8   3.4  1.9   0.2      ｾﾄﾅ
54   5.0   3.2  1.2   0.2      ｾﾄﾅ
56   6.4   2.8  5.6   2.1  ﾊﾞｰｼﾞﾆｶ
58   5.8   4.0  1.2   0.2      ｾﾄﾅ
..   ...   ...  ...   ...      ...
90   5.4   3.9  1.7   0.4      ｾﾄﾅ
92   5.2   2.7  3.9   1.4   ﾊﾞｰｼｸﾙ
94   5.0   3.4  1.5   0.2      ｾﾄﾅ
96   5.0   2.0  3.5   1.0   ﾊﾞｰｼｸﾙ
98   5.8   2.7  3.9   1.2   ﾊﾞｰｼｸﾙ
100  4.6   3.1  1.5   0.2      ｾﾄﾅ
102  6.2   2.9  4.3   1.3   ﾊﾞｰｼｸﾙ
104  5.9   3.0  4.2   1.5   ﾊﾞｰｼｸﾙ
106  5.0   3.5  1.3   0.3      ｾﾄﾅ
108  6.0   2.2  4.0   1.0   ﾊﾞｰｼｸﾙ
110  6.7   2.5  5.8   1.8  ﾊﾞｰｼﾞﾆｶ
112  6.7   3.1  4.7   1.5   ﾊﾞｰｼｸﾙ
114  5.4   3.7  1.5   0.2      ｾﾄﾅ
116  6.3   2.5  4.9   1.5   ﾊﾞｰｼｸﾙ
118  6.4   2.9  4.3   1.3   ﾊﾞｰｼｸﾙ
120  5.7   2.8  4.1   1.3   ﾊﾞｰｼｸﾙ
122  6.9   3.1  5.4   2.1  ﾊﾞｰｼﾞﾆｶ
124  5.1   3.5  1.4   0.3      ｾﾄﾅ
126  6.5   3.2  5.1   2.0  ﾊﾞｰｼﾞﾆｶ
128  5.6   2.9  3.6   1.3   ﾊﾞｰｼｸﾙ
130  6.4   2.7  5.3   1.9  ﾊﾞｰｼﾞﾆｶ
132  5.5   2.5  4.0   1.3   ﾊﾞｰｼｸﾙ
134  4.8   3.0  1.4   0.1      ｾﾄﾅ
136  5.7   2.5  5.0   2.0  ﾊﾞｰｼﾞﾆｶ
138  5.1   3.8  1.5   0.3      ｾﾄﾅ
140  6.6   3.0  4.4   1.4   ﾊﾞｰｼｸﾙ
142  5.4   3.4  1.7   0.2      ｾﾄﾅ
144  5.2   3.5  1.5   0.2      ｾﾄﾅ
146  6.7   3.0  5.0   1.7   ﾊﾞｰｼｸﾙ
148  5.3   3.7  1.5   0.2      ｾﾄﾅ

[75 rows x 5 columns]

In [15]:
data_sepal6 = data[data["がく片"] >= 6]
data_sepal6

がく片  がく片幅  花びら  花びら幅      あやめ
1    6.4   2.8  5.6   2.2  ﾊﾞｰｼﾞﾆｶ
2    6.5   2.8  4.6   1.5   ﾊﾞｰｼｸﾙ
3    6.7   3.1  5.6   2.4  ﾊﾞｰｼﾞﾆｶ
4    6.3   2.8  5.1   1.5  ﾊﾞｰｼﾞﾆｶ
6    6.9   3.1  5.1   2.3  ﾊﾞｰｼﾞﾆｶ
7    6.2   2.2  4.5   1.5   ﾊﾞｰｼｸﾙ
10   6.1   3.0  4.6   1.4   ﾊﾞｰｼｸﾙ
11   6.0   2.7  5.1   1.6   ﾊﾞｰｼｸﾙ
12   6.5   3.0  5.2   2.0  ﾊﾞｰｼﾞﾆｶ
14   6.5   3.0  5.5   1.8  ﾊﾞｰｼﾞﾆｶ
16   6.8   3.2  5.9   2.3  ﾊﾞｰｼﾞﾆｶ
19   6.2   3.4  5.4   2.3  ﾊﾞｰｼﾞﾆｶ
20   7.7   3.8  6.7   2.2  ﾊﾞｰｼﾞﾆｶ
21   6.3   3.3  4.7   1.6   ﾊﾞｰｼｸﾙ
22   6.7   3.3  5.7   2.5  ﾊﾞｰｼﾞﾆｶ
23   7.6   3.0  6.6   2.1  ﾊﾞｰｼﾞﾆｶ
26   6.7   3.0  5.2   2.3  ﾊﾞｰｼﾞﾆｶ
27   7.0   3.2  4.7   1.4   ﾊﾞｰｼｸﾙ
28   6.4   3.2  4.5   1.5   ﾊﾞｰｼｸﾙ
29   6.1   2.8  4.0   1.3   ﾊﾞｰｼｸﾙ
33   6.3   2.5  5.0   1.9  ﾊﾞｰｼﾞﾆｶ
34   6.4   3.2  5.3   2.3  ﾊﾞｰｼﾞﾆｶ
38   7.9   3.8  6.4   2.0  ﾊﾞｰｼﾞﾆｶ
40   6.7   3.3  5.7   2.1  ﾊﾞｰｼﾞﾆｶ
44   7.7   2.8  6.7   2.0  ﾊﾞｰｼﾞﾆｶ
45   6.3   2.7  4.9   1.8  ﾊﾞｰｼﾞﾆｶ
48   7.2   3.2  6.0   1.8  ﾊﾞｰｼﾞﾆｶ
51   6.1   3.0  4.9   1.8  ﾊﾞｰｼﾞﾆｶ
55   6.1   2.6  5.6   1.4  ﾊﾞｰｼﾞﾆｶ
56   6.4   2.8  5.6   2.1  ﾊﾞｰｼﾞﾆｶ
..   ...   ...  ...   ...      ...
80   6.4   3.1  5.5   1.8  ﾊﾞｰｼﾞﾆｶ
81   6.0   3.0  4.8   1.8  ﾊﾞｰｼﾞﾆｶ
82   6.3   2.9  5.6   1.8  ﾊﾞｰｼﾞﾆｶ
88   7.7   2.6  6.9   2.3  ﾊﾞｰｼﾞﾆｶ
89   6.0   2.2  5.0   1.5  ﾊﾞｰｼﾞﾆｶ
91   6.6   2.9  4.6   1.3   ﾊﾞｰｼｸﾙ
93   6.0   3.4  4.5   1.6   ﾊﾞｰｼｸﾙ
101  6.9   3.2  5.7   2.3  ﾊﾞｰｼﾞﾆｶ
102  6.2   2.9  4.3   1.3   ﾊﾞｰｼｸﾙ
103  7.4   2.8  6.1   1.9  ﾊﾞｰｼﾞﾆｶ
108  6.0   2.2  4.0   1.0   ﾊﾞｰｼｸﾙ
109  7.3   2.9  6.3   1.8  ﾊﾞｰｼﾞﾆｶ
110  6.7   2.5  5.8   1.8  ﾊﾞｰｼﾞﾆｶ
112  6.7   3.1  4.7   1.5   ﾊﾞｰｼｸﾙ
113  6.3   2.3  4.4   1.3   ﾊﾞｰｼｸﾙ
116  6.3   2.5  4.9   1.5   ﾊﾞｰｼｸﾙ
117  6.1   2.8  4.7   1.2   ﾊﾞｰｼｸﾙ
118  6.4   2.9  4.3   1.3   ﾊﾞｰｼｸﾙ
121  6.5   3.0  5.8   2.2  ﾊﾞｰｼﾞﾆｶ
122  6.9   3.1  5.4   2.1  ﾊﾞｰｼﾞﾆｶ
125  7.2   3.6  6.1   2.5  ﾊﾞｰｼﾞﾆｶ
126  6.5   3.2  5.1   2.0  ﾊﾞｰｼﾞﾆｶ
127  6.1   2.9  4.7   1.4   ﾊﾞｰｼｸﾙ
129  6.9   3.1  4.9   1.5   ﾊﾞｰｼｸﾙ
130  6.4   2.7  5.3   1.9  ﾊﾞｰｼﾞﾆｶ
131  6.8   3.0  5.5   2.1  ﾊﾞｰｼﾞﾆｶ
140  6.6   3.0  4.4   1.4   ﾊﾞｰｼｸﾙ
141  6.8   2.8  4.8   1.4   ﾊﾞｰｼｸﾙ
146  6.7   3.0  5.0   1.7   ﾊﾞｰｼｸﾙ
147  6.3   3.3  6.0   2.5  ﾊﾞｰｼﾞﾆｶ

[67 rows x 5 columns]

In [16]:
np .arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np .array([2,5,2,6,8,0])

array([2, 5, 2, 6, 8, 0])

In [22]:
matrix = np .arange(100) . reshape(10, 10)
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
matrix[2:6 , 2:8]

array([[22, 23, 24, 25, 26, 27],
       [32, 33, 34, 35, 36, 37],
       [42, 43, 44, 45, 46, 47],
       [52, 53, 54, 55, 56, 57]])

In [20]:
matrix[[0,1,3], :][: ,[0,1,3]]

array([[ 0,  1,  3],
       [10, 11, 13],
       [30, 31, 33]])

In [23]:
matrix2 = np .r_[matrix ,matrix]
matrix2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [26]:
matrix2[matrix2 == 25] = 0
matrix2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24,  0, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24,  0, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])